# Generated by Django 4.1.5 on 2024-07-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_log',
            name='Bottle_loc',
            field=models.CharField(default='Supermarket shelf', max_length=100),
        ),
        migrations.AlterModelTable(
            name='shampooprice',
            table='Shampooprice',
        ),
    ]
