# Generated by Django 5.1.3 on 2025-03-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Password',
            field=models.CharField(max_length=500),
        ),
    ]
