# Generated by Django 5.1.3 on 2025-03-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cityrul_notification',
            field=models.CharField(default='0', max_length=70, null=True),
        ),
    ]
