# Generated by Django 5.1.3 on 2025-01-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='Current_Refill_Count',
            new_name='Current_PlantRefill_Count',
        ),
        migrations.AddField(
            model_name='asset',
            name='Current_SelfRefill_Count',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
