# Generated by Django 5.1.3 on 2025-10-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottleinventory',
            name='stock_updated_day',
            field=models.CharField(blank=True, default=0, max_length=11),
        ),
    ]
