# Generated by Django 5.1.3 on 2025-01-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_current_refill_count_asset_current_plantrefill_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Current_PlantRefill_Count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Current_SelfRefill_Count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
