# Generated by Django 5.1.3 on 2025-03-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Password',
            new_name='password',
        ),
    ]
