# Generated by Django 4.1.5 on 2024-07-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_audit_log_bottle_loc_alter_shampooprice_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_log',
            name='CityId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
