# Generated by Django 4.1.5 on 2023-04-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='User_cityid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
