# Generated by Django 4.1.5 on 2023-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_user_cityid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='User_cityid',
            field=models.CharField(blank=True, default=0, max_length=11),
        ),
    ]
