# Generated by Django 5.1.3 on 2025-01-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_asset_current_plantrefill_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='currentrefillCount',
            new_name='currentplantrefillCount',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='currentselfrefillCount',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
