# Generated by Django 4.1.5 on 2023-04-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_user_cityid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Role',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
