# Generated by Django 5.1.3 on 2025-01-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_currentrefillcount_auditlog_currentplantrefillcount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityrule',
            name='Carbage_display',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='Date_create',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='Dustbin_display',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='Dustbin_penalty',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_C_Brcb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_C_Brfb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_C_Bvb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_C_Urcb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_C_Urfb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_C_Uvb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_P_Brcb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_P_Brfb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_P_Bvb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_P_Urcb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_P_Urfb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_P_Uvb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_P_beverage',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_P_cleaner',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_P_pickle',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_P_shampoo',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_R_Brcb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_R_Brfb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_R_Bvb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_R_Urcb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_R_Urfb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_R_Uvb',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_UB_rc_m',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_UB_v_m',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='EnvTx_UB_xx_c',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='Return_B_B',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='Return_B_G',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='Return_U_B',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='Return_U_G',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='recycledplastic_cost',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='rule_city',
        ),
        migrations.RemoveField(
            model_name='cityrule',
            name='virginplastic_cost',
        ),
        migrations.AddField(
            model_name='cityrule',
            name='cityId',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='day_number',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='display_at_dustbin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='dustbinning_fine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_ub_xx_cl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='fine_for_throwing_bottle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='garbage_truck_announcement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='recycled_plastic_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='rule_number',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='time_in_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='virgin_plastic_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_c_brcb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_c_brfb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_c_bvb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_c_urcb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_c_urfB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_c_uvb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_p_brcb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_p_brfb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_p_bvb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_p_shampoo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_r_brcb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_r_brfb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_r_bvb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_r_urcb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_r_urfB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_r_uvb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_ub_rc_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityrule',
            name='envtx_ub_v_m',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
