# Generated by Django 5.1.3 on 2025-04-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_last_login_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='Container_Amt',
            field=models.CharField(default='0', max_length=70),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='Content_Amt',
            field=models.CharField(default='0', max_length=70),
        ),
    ]
