# Generated by Django 5.1.3 on 2025-04-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cashflow_container_amt_cashflow_content_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='Container_Amt',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='Content_Amt',
            field=models.CharField(default='', max_length=70),
        ),
    ]
