# Generated by Django 5.1.3 on 2025-01-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_cityrule_carbage_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='update_count',
            field=models.IntegerField(default=0),
        ),
    ]
