from django.contrib import admin

from django.urls import include, path
from accounts import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('api/api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', views.login, name='login'),
    path('api/login/', views.login, name='login'),
    path('api/updateusercity/<userid>',views.updateusercity, name='updateusercity'),
    path('api/signup/', views.signup, name='signup'),
    path('api/addcity/', views.addcity, name='addcity'),
    path('api/addcity/<cityid>', views.editcity, name='editcity'),
    path('api/updatetime/<cityid>', views.updatecurrent, name='updatecurrent'),
    path('api/getcityname/<cityid>', views.getcityname, name='getcityname'),
    path('api/facility/<mayorid>', views.facility, name='facility'),
    path('api/getfacility/<cityid>', views.getfacility, name='getfacility'),
    path('api/updatefacility/', views.updatefacility, name='updatefacility'),
    path('api/leavefacility/<userid>', views.leavefacility, name='leavefacility'),
    path('api/asset/<cityid>', views.createasset, name='createasset'),
    path('api/assets/<itemid>', views.returnasset, name='returnasset'),
    path('api/lockasset/<itemid>', views.lockasset, name='lockasset'),
    path('api/unlockasset/<itemid>', views.unlockasset, name='unlockasset'),
    path('api/update_city_threads/', views.update_city_threads, name='update_city_threads'),
    #path('api/receive_user_details/', views.receive_user_data, name='receive_user_data'),
    path('api/cashflow/', views.createtransaction, name='createtransaction'),
    path('api/audit-log/<asset_id>/', views.get_audit_logs, name='get_audit_logs'),
    path('api/audit-logs/<user>/', views.get_audit_logsuser, name='get_audit_logsuser'),
    path('api/bottleprice/', views.get_BottlePrice, name='get_BottlePrice'),
    path('api/shampooprice/', views.get_ShampooPrice, name='get_ShampooPrice'),
    path('api/updatetransactionfacility/<cityid>',views.updatetransactionfacility, name='updatetransactionfacility'),
    path('api/getsupermarketcash/<cityid>',views.getsupermarketcash, name='getsupermarketcash'),
    path('api/getmunicipalitycash/<cityid>',views.getmunicipalitycash, name='getmunicipalitycash'),
    path('api/getrefillingstationcash/<cityid>',views.getrefillingstationcash, name='getrefillingstationcash'),
    path('api/getreversevendingcash/<cityid>',views.getreversevendingcash, name='getreversevendingcash'),
    path('api/filter-audit-logs/', views.filter_audit_logs, name='filter_audit_logs'),
    path('api/filter-options/', views.get_filter_options, name='get_filter_options'),
    path('api/addRule/', views.add_Cityrule, name='add_Cityrule'),
]
